name: DEV - CICD

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "main"
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

env:
  IMAGE_NAME: "example1" # Required
  IMAGE_TAG: "0.1" # Required
  GO111MODULE: on
  
jobs:
  cicd:
    name: CI-CD
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      actions: read
      packages: write
      # required for all workflows
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.17.6' # The Go version to download (if necessary) and use.

    - run: |
        go version

    - name: Install dependencies
      run: |
        go env -w GO111MODULE=on
        go get
        go mod vendor
    
    - name: Unit test
      run: |
        go test -coverprofile coverage.out ./...
        go tool cover -html coverage.out -o report.html

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results
        path: '${{ github.workspace }}/report.html'

    - name: Build image
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: false
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{env.IMAGE_TAG}}
    
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_ID:$IMAGE_TAG
        docker push $IMAGE_ID:$IMAGE_TAG

    - name: Deploy
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo DEPLOY $IMAGE_NAME:$IMAGE_TAG
        docker run $IMAGE_NAME:$IMAGE_TAG